package Interfaces;


import Action.go;
import static Action.go.getCurrentUser;
import MainPackage.*;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import MainPackage.User;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Obaida
 */
public class HomeScreen extends javax.swing.JFrame {
  public static int SCROLL_INCREMENT_SPEED =16;
  public static int CATAGORY_LENGTH = 1;
  public static int MOVIE_SAPERATOR =30;
  public CardLayout cardLayout;
  /**
   * Creates new form LoginScreen
   */
  public HomeScreen() {
    setting();
    initComponents();
    this.setVisible(true);
    User user =getCurrentUser();
    userNameLabel.setText(user.getUserName());
    AddressLbl.setText(user.getUserAddress());
    AccountIDLbl.setText("192.175."+user.getUserID());
    this.setIcons(true, false, false);
    cardLayout = (CardLayout)(pageCardPanel.getLayout());
    this.setUserData();
//    User user = getCurrentUser();
    userTicketCount.setText(String.valueOf(user.getUserBookedTickets().size()));
  }

  public void setting(){
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlebar = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        seperator3 = new javax.swing.JPanel();
        pageCardPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homeScrollPane = new javax.swing.JScrollPane();
        homeScrollPanel = new javax.swing.JPanel();
        actionScrollPane = new javax.swing.JScrollPane();
        gapPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        seperator1 = new javax.swing.JPanel();
        arrowLeft1 = new javax.swing.JLabel();
        arrowRight1 = new javax.swing.JLabel();
        romanceScrollPane = new javax.swing.JScrollPane();
        gapPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        seperator2 = new javax.swing.JPanel();
        arrowLeft2 = new javax.swing.JLabel();
        arrowRight2 = new javax.swing.JLabel();
        dramaScrollPane = new javax.swing.JScrollPane();
        gapPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        seperator4 = new javax.swing.JPanel();
        arrowLeft3 = new javax.swing.JLabel();
        arrowRight3 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panClick = new javax.swing.JPanel();
        lblClick = new javax.swing.JLabel();
        userTicketCount = new javax.swing.JLabel();
        userAddressLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        panClick1 = new javax.swing.JPanel();
        lblClick1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        AddressLbl = new javax.swing.JLabel();
        AccountIDLbl = new javax.swing.JLabel();
        settingsPanel = new javax.swing.JPanel();
        changePasswordLabel = new javax.swing.JLabel();
        hidenpw1 = new javax.swing.JLabel();
        pwLable1 = new javax.swing.JLabel();
        pwLine1 = new javax.swing.JLabel();
        txtpw1 = new javax.swing.JPasswordField();
        shownpw1 = new javax.swing.JLabel();
        txtpw2 = new javax.swing.JPasswordField();
        hidenpw2 = new javax.swing.JLabel();
        pwLine2 = new javax.swing.JLabel();
        shownpw2 = new javax.swing.JLabel();
        pwLable2 = new javax.swing.JLabel();
        changepwBtn = new JButton() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();

                // هاد رح يكون اوبجيكت من كلاس جاهز فيو الشكل يلي بيعطي حواف مدورة ويلي رح نمررو لتابع بعد كم سطر
                int arcDiameter = getHeight();
                RoundRectangle2D roundRect = new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), arcDiameter, arcDiameter);

                // هي التريك المسؤولة عن تغير اللون
                if (getModel().isArmed()) {
                    g2.setColor(new Color(107, 73, 117)); // لون عند الضغط
                } else if (getModel().isRollover()) {
                    g2.setColor(new Color(157, 121, 168)); // لون عند التحويل
                } else {
                    g2.setColor(new Color(251,251,253)); // اللون الافتراضي
                }
                // هون حددنا الشكل يلي بدنا ياه يكون للزر
                g2.fill(roundRect);

                // الخط والالوان
                g2.setColor(Color.BLACK);
                g2.setFont(new Font("Trebuchet MS", 0, 16));

                // خوارزمية جاهزة لهتى تكون الجملة بمنتصف الزر
                FontMetrics fm = g.getFontMetrics();
                String text = getText();
                int textWidth = fm.stringWidth(text);
                int textHeight = fm.getHeight();

                int x = (getWidth() - textWidth) / 2;
                int y = (getHeight() - textHeight) / 2 + fm.getAscent();

                // اذا ع التجربة ما حسيناها كتير راكزة ممكن نضيف او نطرح ع ال y  و ال x  يلي هون
                g2.drawString(text, x, y);

                g2.dispose();
            }
        };
        ;
        changetxt = new javax.swing.JLabel();
        changepwBtn1 = new JButton() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();

                // هاد رح يكون اوبجيكت من كلاس جاهز فيو الشكل يلي بيعطي حواف مدورة ويلي رح نمررو لتابع بعد كم سطر
                int arcDiameter = getHeight();
                RoundRectangle2D roundRect = new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), arcDiameter, arcDiameter);

                // هي التريك المسؤولة عن تغير اللون
                if (getModel().isArmed()) {
                    g2.setColor(new Color(255,30,30)); // لون عند الضغط
                } else if (getModel().isRollover()) {
                    g2.setColor(new Color(255, 75, 75)); // لون عند التحويل
                } else {
                    g2.setColor(new Color(255,100,140)); // اللون الافتراضي
                }
                // هون حددنا الشكل يلي بدنا ياه يكون للزر
                g2.fill(roundRect);

                // الخط والالوان
                g2.setColor(Color.BLACK);
                g2.setFont(new Font("Trebuchet MS", 0, 16));

                // خوارزمية جاهزة لهتى تكون الجملة بمنتصف الزر
                FontMetrics fm = g.getFontMetrics();
                String text = getText();
                int textWidth = fm.stringWidth(text);
                int textHeight = fm.getHeight();

                int x = (getWidth() - textWidth) / 2;
                int y = (getHeight() - textHeight) / 2 + fm.getAscent();

                // اذا ع التجربة ما حسيناها كتير راكزة ممكن نضيف او نطرح ع ال y  و ال x  يلي هون
                g2.drawString(text, x, y);

                g2.dispose();
            }
        };
        ;
        sidebar = new javax.swing.JPanel();
        userIcn = new javax.swing.JLabel();
        homeIcnDefault = new javax.swing.JLabel();
        moviesIcnDefault = new javax.swing.JLabel();
        settingsIcnDefault = new javax.swing.JLabel();
        homeIcnSelected = new javax.swing.JLabel();
        moviesIcnSelected = new javax.swing.JLabel();
        settingsIcnSelected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(4, 15, 19));
        mainPanel.setLayout(new java.awt.BorderLayout());

        titlebar.setBackground(new java.awt.Color(4, 15, 19));

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("X");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });

        seperator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

        javax.swing.GroupLayout seperator3Layout = new javax.swing.GroupLayout(seperator3);
        seperator3.setLayout(seperator3Layout);
        seperator3Layout.setHorizontalGroup(
            seperator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1126, Short.MAX_VALUE)
        );
        seperator3Layout.setVerticalGroup(
            seperator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout titlebarLayout = new javax.swing.GroupLayout(titlebar);
        titlebar.setLayout(titlebarLayout);
        titlebarLayout.setHorizontalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlebarLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        titlebarLayout.setVerticalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebarLayout.createSequentialGroup()
                .addGroup(titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(titlebar, java.awt.BorderLayout.PAGE_START);

        pageCardPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(4, 15, 22));

        homeScrollPane.setBackground(new java.awt.Color(4, 15, 22));
        homeScrollPane.getViewport().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
        homeScrollPane.setBorder(null);
        homeScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        homeScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        homeScrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0));
        homeScrollPane.getVerticalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);
        homeScrollPane.setEnabled(false);

        homeScrollPanel.setBackground(new java.awt.Color(4, 15, 22));
        homeScrollPanel.setPreferredSize(new java.awt.Dimension(500, 950));

        actionScrollPane.setBackground(new Color(0,0,0,1));
        actionScrollPane.getViewport ().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
        actionScrollPane.setBorder(null);
        actionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        actionScrollPane.setPreferredSize(new java.awt.Dimension(200, 100));
        actionScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 0));
        actionScrollPane.getHorizontalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);

        gapPanel1.setBackground(new Color(0,0,0,1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOP Action");

        seperator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

        javax.swing.GroupLayout seperator1Layout = new javax.swing.GroupLayout(seperator1);
        seperator1.setLayout(seperator1Layout);
        seperator1Layout.setHorizontalGroup(
            seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        seperator1Layout.setVerticalGroup(
            seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gapPanel1Layout = new javax.swing.GroupLayout(gapPanel1);
        gapPanel1.setLayout(gapPanel1Layout);
        gapPanel1Layout.setHorizontalGroup(
            gapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gapPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gapPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gapPanel1Layout.setVerticalGroup(
            gapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapPanel1Layout.createSequentialGroup()
                .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gapPanel1.setSize(300, 70);

        arrowLeft1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowLeft1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowLeftDefault-01.png"))); // NOI18N
        arrowLeft1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowLeft1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowLeft1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowLeft1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arrowLeft1MousePressed(evt);
            }
        });

        arrowRight1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowRight1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowRightDefault-01.png"))); // NOI18N
        arrowRight1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowRight1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowRight1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowRight1MouseExited(evt);
            }
        });

        romanceScrollPane.setBackground(new Color(0,0,0,1));
        romanceScrollPane.getViewport().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
        romanceScrollPane.setBorder(null);
        romanceScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        romanceScrollPane.setPreferredSize(new java.awt.Dimension(200, 100));
        romanceScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 0));
        romanceScrollPane.getHorizontalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);

        gapPanel2.setBackground(new Color(0,0,0,1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOP Romance");

        seperator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

        javax.swing.GroupLayout seperator2Layout = new javax.swing.GroupLayout(seperator2);
        seperator2.setLayout(seperator2Layout);
        seperator2Layout.setHorizontalGroup(
            seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        seperator2Layout.setVerticalGroup(
            seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gapPanel2Layout = new javax.swing.GroupLayout(gapPanel2);
        gapPanel2.setLayout(gapPanel2Layout);
        gapPanel2Layout.setHorizontalGroup(
            gapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gapPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gapPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gapPanel2Layout.setVerticalGroup(
            gapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapPanel2Layout.createSequentialGroup()
                .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gapPanel1.setSize(300, 70);

        arrowLeft2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowLeft2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowLeftDefault-01.png"))); // NOI18N
        arrowLeft2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowLeft2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowLeft2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowLeft2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arrowLeft2MousePressed(evt);
            }
        });

        arrowRight2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowRight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowRightDefault-01.png"))); // NOI18N
        arrowRight2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowRight2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowRight2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowRight2MouseExited(evt);
            }
        });

        dramaScrollPane.setBackground(new Color(0,0,0,1));
        dramaScrollPane.getViewport().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
        dramaScrollPane.setBorder(null);
        dramaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        dramaScrollPane.setPreferredSize(new java.awt.Dimension(200, 100));
        dramaScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 0));
        dramaScrollPane.getHorizontalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);

        addRowScrollPanel2();
        homeScrollPanel.add(gapPanel2);
        homeScrollPanel.add(dramaScrollPane);

        gapPanel3.setBackground(new Color(0,0,0,1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOP Drama");

        seperator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

        javax.swing.GroupLayout seperator4Layout = new javax.swing.GroupLayout(seperator4);
        seperator4.setLayout(seperator4Layout);
        seperator4Layout.setHorizontalGroup(
            seperator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        seperator4Layout.setVerticalGroup(
            seperator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gapPanel3Layout = new javax.swing.GroupLayout(gapPanel3);
        gapPanel3.setLayout(gapPanel3Layout);
        gapPanel3Layout.setHorizontalGroup(
            gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gapPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gapPanel3Layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );
        gapPanel3Layout.setVerticalGroup(
            gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gapPanel3Layout.createSequentialGroup()
                    .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 82, Short.MAX_VALUE)))
        );

        gapPanel1.setSize(300, 70);

        arrowLeft3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowLeft3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowLeftDefault-01.png"))); // NOI18N
        arrowLeft3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowLeft3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowLeft3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowLeft3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arrowLeft3MousePressed(evt);
            }
        });

        arrowRight3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowRight3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowRightDefault-01.png"))); // NOI18N
        arrowRight3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowRight3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowRight3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowRight3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout homeScrollPanelLayout = new javax.swing.GroupLayout(homeScrollPanel);
        homeScrollPanel.setLayout(homeScrollPanelLayout);
        homeScrollPanelLayout.setHorizontalGroup(
            homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gapPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gapPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gapPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homeScrollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeScrollPanelLayout.createSequentialGroup()
                        .addComponent(arrowLeft2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(romanceScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(arrowRight2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeScrollPanelLayout.createSequentialGroup()
                        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arrowLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrowLeft3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeScrollPanelLayout.createSequentialGroup()
                                .addComponent(dramaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(arrowRight3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(homeScrollPanelLayout.createSequentialGroup()
                                .addComponent(actionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(arrowRight1)))))
                .addContainerGap())
        );
        homeScrollPanelLayout.setVerticalGroup(
            homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeScrollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gapPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(actionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeScrollPanelLayout.createSequentialGroup()
                        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(arrowLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrowRight1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addGap(37, 37, 37)
                .addComponent(gapPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(romanceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeScrollPanelLayout.createSequentialGroup()
                        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(arrowLeft2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrowRight2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(gapPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeScrollPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(homeScrollPanelLayout.createSequentialGroup()
                                .addComponent(arrowRight3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(homeScrollPanelLayout.createSequentialGroup()
                                .addComponent(arrowLeft3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addGroup(homeScrollPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dramaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        addRowScrollPanel1();
        homeScrollPanel.add(gapPanel1);
        homeScrollPanel.add(actionScrollPane);
        addRowScrollPanel3();
        homeScrollPanel.add(gapPanel3);
        homeScrollPanel.add(romanceScrollPane);
        addRowScrollPanel2();

        //homeScrollPanel.setLayout(new GridLayout(0, 1, 10, 0));

        homeScrollPane.setViewportView(homeScrollPanel);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1241, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pageCardPanel.add(homePanel, "CardHome");

        userPanel.setBackground(new java.awt.Color(4, 15, 22));
        userPanel.setPreferredSize(new java.awt.Dimension(1241, 608));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 251, 255));
        jLabel1.setText("Address :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 251, 255));
        jLabel5.setText("Booked Tickets");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 251, 255));
        jLabel6.setText("Account ID  :");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Ali UserImage3.png"))); // NOI18N

        panClick.setBackground(new java.awt.Color(251, 251, 255));
        panClick.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 3));
        panClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panClickMouseExited(evt);
            }
        });

        lblClick.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblClick.setText("View My Tickets ");
        lblClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClickMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panClickLayout = new javax.swing.GroupLayout(panClick);
        panClick.setLayout(panClickLayout);
        panClickLayout.setHorizontalGroup(
            panClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClick)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panClickLayout.setVerticalGroup(
            panClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClick)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userTicketCount.setFont(new java.awt.Font("Stencil", 1, 100)); // NOI18N
        userTicketCount.setForeground(new java.awt.Color(251, 251, 255));
        userTicketCount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        userTicketCount.setText("5");

        userAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userAddressLabel.setForeground(new java.awt.Color(251, 251, 255));

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(251, 251, 255));
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        userIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userIdLabel.setForeground(new java.awt.Color(251, 251, 255));

        panClick1.setBackground(new java.awt.Color(251, 251, 255));
        panClick1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 3));
        panClick1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panClick1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panClick1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panClick1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panClick1MouseExited(evt);
            }
        });

        lblClick1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblClick1.setText("Cancel Ticket");
        lblClick1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClick1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClick1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClick1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panClick1Layout = new javax.swing.GroupLayout(panClick1);
        panClick1.setLayout(panClick1Layout);
        panClick1Layout.setHorizontalGroup(
            panClick1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panClick1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClick1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panClick1Layout.setVerticalGroup(
            panClick1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClick1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tape1.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/filming1.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/glasses.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/drink.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tablet.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tape2.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/filming3.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tape1.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Popcorn.png"))); // NOI18N
        jLabel20.setText("jLabel19");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tablet.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/filming2.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tape2.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/filming2.png"))); // NOI18N
        jLabel25.setText("jLabel19");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Popcorn.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/clipart1.png"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tape2.png"))); // NOI18N

        AddressLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddressLbl.setText("jaramana");

        AccountIDLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AccountIDLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccountIDLbl.setText("192.175.1");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addComponent(userAddressLabel)
                                        .addGap(203, 203, 203)
                                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addComponent(userIdLabel)
                                        .addGap(33, 33, 33)
                                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AccountIDLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panClick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(484, 484, Short.MAX_VALUE))
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel7)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(0, 245, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userPanelLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel19)
                                .addGap(0, 313, Short.MAX_VALUE))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userTicketCount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(panClick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userPanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55))))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(884, Short.MAX_VALUE))))
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                            .addComponent(userAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88))
                        .addComponent(userIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panClick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(AccountIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addComponent(AddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)))
                        .addGap(5, 5, 5)))
                .addGap(130, 130, 130))
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(503, 503, 503))
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(userPanelLayout.createSequentialGroup()
                            .addGap(198, 198, 198)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(userPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19))
                                .addGroup(userPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addComponent(userTicketCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );

        pageCardPanel.add(userPanel, "CardUser");

        settingsPanel.setBackground(new java.awt.Color(4, 15, 19));

        changePasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        changePasswordLabel.setForeground(new java.awt.Color(251, 251, 255));
        changePasswordLabel.setText("Change Password...");

        hidenpw1.setBackground(new Color(0,0,0,0));
        hidenpw1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/EyeHide.png"))); // NOI18N
        hidenpw1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidenpw1.setOpaque(true);
        hidenpw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidenpw1MouseClicked(evt);
            }
        });

        pwLable1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        pwLable1.setForeground(new java.awt.Color(255, 255, 255));
        pwLable1.setText("New Password");

        pwLine1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pwLine1.setForeground(new java.awt.Color(255, 255, 255));
        pwLine1.setText("______________________________");

        txtpw1.setBackground(new Color(0,0,0,1));
        txtpw1.setForeground(new java.awt.Color(255, 255, 255));
        txtpw1.setBorder(null);
        txtpw1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpw1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        shownpw1.setVisible(false);
        shownpw1.setEnabled(false);
        hidenpw1.setVisible(true);
        hidenpw1.setEnabled(true);
        shownpw1.setBackground(new Color(0,0,0,0));
        shownpw1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/EyeShow.png"))); // NOI18N
        shownpw1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shownpw1.setOpaque(true);
        shownpw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shownpw1MouseClicked(evt);
            }
        });

        txtpw2.setBackground(new Color(0,0,0,1));
        txtpw2.setForeground(new java.awt.Color(255, 255, 255));
        txtpw2.setBorder(null);
        txtpw2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpw2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        shownpw2.setVisible(false);
        shownpw2.setEnabled(false);
        hidenpw2.setVisible(true);
        hidenpw2.setEnabled(true);
        hidenpw2.setBackground(new Color(0,0,0,0));
        hidenpw2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/EyeHide.png"))); // NOI18N
        hidenpw2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidenpw2.setOpaque(true);
        hidenpw2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidenpw2MouseClicked(evt);
            }
        });

        pwLine2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pwLine2.setForeground(new java.awt.Color(255, 255, 255));
        pwLine2.setText("______________________________");

        shownpw2.setBackground(new Color(0,0,0,0));
        shownpw2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/EyeShow.png"))); // NOI18N
        shownpw2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shownpw2.setOpaque(true);
        shownpw2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shownpw2MouseClicked(evt);
            }
        });

        pwLable2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        pwLable2.setForeground(new java.awt.Color(255, 255, 255));
        pwLable2.setText("Confirm Password");

        changepwBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        changepwBtn.setText(" Change Password");
        changepwBtn.setBorder(null);
        changepwBtn.setBorderPainted(false);
        changepwBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changepwBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changepwBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepwBtnActionPerformed(evt);
            }
        });

        changepwBtn1.setBackground(new java.awt.Color(255, 102, 102));
        changepwBtn1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        changepwBtn1.setText("Log out");
        changepwBtn1.setBorder(null);
        changepwBtn1.setBorderPainted(false);
        changepwBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changepwBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changepwBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepwBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(changePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                            .addGap(222, 222, 222)
                            .addComponent(pwLable1))
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                            .addGap(222, 222, 222)
                            .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pwLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(txtpw2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hidenpw2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(shownpw2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pwLable2))
                                .addGroup(settingsPanelLayout.createSequentialGroup()
                                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pwLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(settingsPanelLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(txtpw1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(30, 30, 30)
                                    .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hidenpw1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(shownpw1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                            .addGap(448, 448, 448)
                            .addComponent(changepwBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(631, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(changepwBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(changePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pwLable1)
                .addGap(2, 2, 2)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pwLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtpw1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hidenpw1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shownpw1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pwLable2)
                .addGap(2, 2, 2)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pwLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtpw2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hidenpw2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shownpw2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changepwBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(changepwBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pageCardPanel.add(settingsPanel, "CardSettings");

        mainPanel.add(pageCardPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        sidebar.setBackground(new java.awt.Color(251, 251, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(60, 371));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIcn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/userDefault.png"))); // NOI18N
        userIcn.setPreferredSize(new java.awt.Dimension(60, 60));
        userIcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userIcnMouseClicked(evt);
            }
        });
        sidebar.add(userIcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        homeIcnDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeIcnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/homeDefault.png"))); // NOI18N
        homeIcnDefault.setEnabled(false);
        homeIcnDefault.setPreferredSize(new java.awt.Dimension(60, 40));
        homeIcnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIcnDefaultMouseClicked(evt);
            }
        });
        sidebar.add(homeIcnDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, -1, -1));

        moviesIcnDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moviesIcnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/movieDefault.png"))); // NOI18N
        moviesIcnDefault.setPreferredSize(new java.awt.Dimension(60, 40));
        moviesIcnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviesIcnDefaultMouseClicked(evt);
            }
        });
        sidebar.add(moviesIcnDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, -1, -1));

        settingsIcnDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsIcnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sittingsDefault.png"))); // NOI18N
        settingsIcnDefault.setPreferredSize(new java.awt.Dimension(60, 40));
        settingsIcnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsIcnDefaultMouseClicked(evt);
            }
        });
        sidebar.add(settingsIcnDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, 60, -1));

        homeIcnSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeIcnSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/homeSelected.png"))); // NOI18N
        homeIcnSelected.setPreferredSize(new java.awt.Dimension(60, 40));
        sidebar.add(homeIcnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        moviesIcnSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moviesIcnSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/movieSelected.png"))); // NOI18N
        sidebar.add(moviesIcnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, -1, -1));

        settingsIcnSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsIcnSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sittingsSelected.png"))); // NOI18N
        settingsIcnSelected.setPreferredSize(new java.awt.Dimension(60, 40));
        sidebar.add(settingsIcnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, -1));

        getContentPane().add(sidebar, java.awt.BorderLayout.WEST);

        setSize(new java.awt.Dimension(1301, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
    System.exit(0);
  }//GEN-LAST:event_exitButtonMouseClicked

  private void arrowLeft2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MouseClicked
//    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftClick-01.png"));
    JScrollBar horizontalScrollBar = romanceScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() - SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowLeft2MouseClicked

  private void arrowRight2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight2MouseClicked
//    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightClick-01.png"));
    JScrollBar horizontalScrollBar = romanceScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() + SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowRight2MouseClicked

  private void arrowLeft2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MouseEntered
    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftHover-01.png"));
  }//GEN-LAST:event_arrowLeft2MouseEntered

  private void arrowLeft2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MouseExited
    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftDefault-01.png"));
  }//GEN-LAST:event_arrowLeft2MouseExited

  private void arrowRight2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight2MouseEntered
    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightHover-01.png"));
  }//GEN-LAST:event_arrowRight2MouseEntered

  private void arrowRight2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight2MouseExited
    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightDefault-01.png"));
  }//GEN-LAST:event_arrowRight2MouseExited

  private void arrowLeft2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_arrowLeft2MousePressed

  private void arrowLeft3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MouseClicked
//    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftClick-01.png"));
    JScrollBar horizontalScrollBar = dramaScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() - SCROLL_INCREMENT_SPEED*5);  }//GEN-LAST:event_arrowLeft3MouseClicked

  private void arrowLeft3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MouseEntered
    arrowLeft3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftHover-01.png"));
  }//GEN-LAST:event_arrowLeft3MouseEntered

  private void arrowLeft3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MouseExited
    arrowLeft3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftDefault-01.png"));
  }//GEN-LAST:event_arrowLeft3MouseExited

  private void arrowLeft3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_arrowLeft3MousePressed

  private void arrowRight3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight3MouseClicked
//    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightClick-01.png"));
    JScrollBar horizontalScrollBar = dramaScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() + SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowRight3MouseClicked

  private void arrowRight3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight3MouseEntered
    arrowRight3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightHover-01.png"));
  }//GEN-LAST:event_arrowRight3MouseEntered

  private void arrowRight3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight3MouseExited
    arrowRight3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightDefault-01.png"));
  }//GEN-LAST:event_arrowRight3MouseExited

  private void arrowLeft1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_arrowLeft1MousePressed

  private void arrowLeft1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MouseExited
    arrowLeft1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftDefault-01.png"));
  }//GEN-LAST:event_arrowLeft1MouseExited

  private void arrowLeft1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MouseEntered
    arrowLeft1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftHover-01.png"));
  }//GEN-LAST:event_arrowLeft1MouseEntered

  private void arrowLeft1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MouseClicked
    //    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftClick-01.png"));
    JScrollBar horizontalScrollBar = actionScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() - SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowLeft1MouseClicked

  private void arrowRight1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight1MouseExited
    arrowRight1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightDefault-01.png"));
  }//GEN-LAST:event_arrowRight1MouseExited

  private void arrowRight1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight1MouseEntered
    arrowRight1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightHover-01.png"));
  }//GEN-LAST:event_arrowRight1MouseEntered

  private void arrowRight1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight1MouseClicked
    //    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightClick-01.png"));
    JScrollBar horizontalScrollBar = actionScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() + SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowRight1MouseClicked

  private void homeIcnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIcnDefaultMouseClicked
    setIcons(true, false, false);
    cardLayout.show(pageCardPanel, "CardHome");
  }//GEN-LAST:event_homeIcnDefaultMouseClicked

  private void moviesIcnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviesIcnDefaultMouseClicked
    setIcons(false, true, false);
    //open movie panel
  }//GEN-LAST:event_moviesIcnDefaultMouseClicked

  private void settingsIcnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsIcnDefaultMouseClicked
    setIcons(false, false, true);
    cardLayout.show(pageCardPanel, "CardSettings");
  }//GEN-LAST:event_settingsIcnDefaultMouseClicked

  private void userIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIcnMouseClicked
    setIcons(false, false, false);
    cardLayout.show(pageCardPanel, "CardUser");
  }//GEN-LAST:event_userIcnMouseClicked

  private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
    exitButton.setForeground(new Color(162,0,255));
  }//GEN-LAST:event_exitButtonMouseEntered

  private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
    exitButton.setForeground(new Color(251,251,255));
  }//GEN-LAST:event_exitButtonMouseExited

  private void lblClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickMouseEntered
    lblClick.setForeground(Color.white);
    panClick.setBackground(new Color(153,0,255));
  }//GEN-LAST:event_lblClickMouseEntered

  private void lblClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickMouseExited
    lblClick.setForeground(Color.BLACK);
  }//GEN-LAST:event_lblClickMouseExited

  private void panClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClickMouseEntered
    panClick.setBackground(new Color(153,0,255));
    lblClick.setForeground(Color.WHITE);
  }//GEN-LAST:event_panClickMouseEntered

  private void panClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClickMouseExited
    panClick.setBackground(new Color(251,251,255));
    lblClick.setForeground(Color.BLACK);
  }//GEN-LAST:event_panClickMouseExited

  private void lblClick1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClick1MouseEntered
    lblClick1.setForeground(Color.white);
    panClick1.setBackground(new Color(153,0,255));
  }//GEN-LAST:event_lblClick1MouseEntered

  private void lblClick1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClick1MouseExited
    panClick1.setBackground(new Color(251,251,255));
    lblClick1.setForeground(Color.BLACK);
  }//GEN-LAST:event_lblClick1MouseExited

  private void panClick1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClick1MouseEntered
    lblClick1.setForeground(Color.white);
    panClick1.setBackground(new Color(153,0,255));
  }//GEN-LAST:event_panClick1MouseEntered

  private void panClick1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClick1MouseExited
    panClick1.setBackground(new Color(251,251,255));
    lblClick1.setForeground(Color.BLACK);
  }//GEN-LAST:event_panClick1MouseExited

  private void hidenpw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidenpw1MouseClicked
    txtpw1.setEchoChar((char)0);
    shownpw1.setVisible(true);
    shownpw1.setEnabled(true);
    hidenpw1.setVisible(false);
    hidenpw1.setEnabled(false);
  }//GEN-LAST:event_hidenpw1MouseClicked

  private void shownpw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shownpw1MouseClicked
    txtpw1.setEchoChar((char)8226);
    shownpw1.setVisible(false);
    shownpw1.setEnabled(false);
    hidenpw1.setVisible(true);
    hidenpw1.setEnabled(true);
  }//GEN-LAST:event_shownpw1MouseClicked

  private void hidenpw2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidenpw2MouseClicked
    txtpw2.setEchoChar((char)0);
    shownpw2.setVisible(true);
    shownpw2.setEnabled(true);
    hidenpw2.setVisible(false);
    hidenpw2.setEnabled(false);
  }//GEN-LAST:event_hidenpw2MouseClicked

  private void shownpw2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shownpw2MouseClicked
    txtpw2.setEchoChar((char)8226);
    shownpw2.setVisible(false);
    shownpw2.setEnabled(false);
    hidenpw2.setVisible(true);
    hidenpw2.setEnabled(true);
  }//GEN-LAST:event_shownpw2MouseClicked

  private void changepwBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepwBtnActionPerformed
    String password = new String(txtpw1.getPassword());
    if(!password.equals(new String(txtpw2.getPassword()))){
      changetxt.setForeground(new Color(255, 102, 102));
      changetxt.setText("Your Password Confirm is incurrect");
      return;
    }
    //Call setPassword()
    changetxt.setForeground(new Color(51, 204, 0));
    changetxt.setText("Your password is successfuly changed");
  }//GEN-LAST:event_changepwBtnActionPerformed

  private void panClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClickMouseClicked
    new my_tickets_form();
  }//GEN-LAST:event_panClickMouseClicked

  private void panClick1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClick1MouseClicked

  }//GEN-LAST:event_panClick1MouseClicked

  private void lblClick1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClick1MouseClicked
    new cancel_ticket_form();
  }//GEN-LAST:event_lblClick1MouseClicked

  private void changepwBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepwBtn1ActionPerformed
    new LoginScreen();
    this.dispose();
  }//GEN-LAST:event_changepwBtn1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountIDLbl;
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JScrollPane actionScrollPane;
    private javax.swing.JLabel arrowLeft1;
    private javax.swing.JLabel arrowLeft2;
    private javax.swing.JLabel arrowLeft3;
    private javax.swing.JLabel arrowRight1;
    private javax.swing.JLabel arrowRight2;
    private javax.swing.JLabel arrowRight3;
    private javax.swing.JLabel changePasswordLabel;
    private javax.swing.JButton changepwBtn;
    private javax.swing.JButton changepwBtn1;
    private javax.swing.JLabel changetxt;
    private javax.swing.JScrollPane dramaScrollPane;
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel gapPanel1;
    private javax.swing.JPanel gapPanel2;
    private javax.swing.JPanel gapPanel3;
    private javax.swing.JLabel hidenpw1;
    private javax.swing.JLabel hidenpw2;
    private javax.swing.JLabel homeIcnDefault;
    private javax.swing.JLabel homeIcnSelected;
    private javax.swing.JPanel homePanel;
    private javax.swing.JScrollPane homeScrollPane;
    private javax.swing.JPanel homeScrollPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblClick;
    private javax.swing.JLabel lblClick1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel moviesIcnDefault;
    private javax.swing.JLabel moviesIcnSelected;
    private javax.swing.JPanel pageCardPanel;
    private javax.swing.JPanel panClick;
    private javax.swing.JPanel panClick1;
    private javax.swing.JLabel pwLable1;
    private javax.swing.JLabel pwLable2;
    private javax.swing.JLabel pwLine1;
    private javax.swing.JLabel pwLine2;
    private javax.swing.JScrollPane romanceScrollPane;
    private javax.swing.JPanel seperator1;
    private javax.swing.JPanel seperator2;
    private javax.swing.JPanel seperator3;
    private javax.swing.JPanel seperator4;
    private javax.swing.JLabel settingsIcnDefault;
    private javax.swing.JLabel settingsIcnSelected;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JLabel shownpw1;
    private javax.swing.JLabel shownpw2;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel titlebar;
    private javax.swing.JPasswordField txtpw1;
    private javax.swing.JPasswordField txtpw2;
    private javax.swing.JLabel userAddressLabel;
    private javax.swing.JLabel userIcn;
    private javax.swing.JLabel userIdLabel;
    public static javax.swing.JLabel userNameLabel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel userTicketCount;
    // End of variables declaration//GEN-END:variables

  
  
  void addRowScrollPanel1(){
    actionScrollPane.setViewportView(new rowScrollPanel(MainPackage.Type.Action));
  }
  void addRowScrollPanel2(){
    dramaScrollPane.setViewportView(new rowScrollPanel(MainPackage.Type.Drama));
  }
  void addRowScrollPanel3(){
    romanceScrollPane.setViewportView(new rowScrollPanel(MainPackage.Type.Romance));
  }

  private void setIcons(boolean home, boolean movies, boolean settings) {
    homeIcnDefault.setVisible(!home);
    homeIcnDefault.setEnabled(!home);
    homeIcnSelected.setVisible(home);
    homeIcnSelected.setEnabled(home);
    
    moviesIcnDefault.setVisible(!movies);
    moviesIcnDefault.setEnabled(!movies);
    moviesIcnSelected.setVisible(movies);
    moviesIcnSelected.setEnabled(movies);
    
    settingsIcnDefault.setVisible(!settings);
    settingsIcnDefault.setEnabled(!settings);
    settingsIcnSelected.setVisible(settings);
    settingsIcnSelected.setEnabled(settings);  
  }

  private void setUserData() {
    // here we need to get the active user so we can display his info
    //User user = getActiveUser();
    
//    userNameLabel.setText(user.getUserName());
//    userAddressLabel.setText(user.getUserAddress());
//    userIdLabel.setText(Integer.toString(user.getUserID()));
//    userTicketCount.setText(Integer.toString(user.getUserBookedTickets().size()));
  }
}

class rowScrollPanel extends JPanel{
  
  Type type;
  
  rowScrollPanel(Type type){
    this.type = type;
    
    this.setBackground(new java.awt.Color(0,0,0,1));
    this.setForeground(new java.awt.Color(255, 255, 255));
    this.setLayout(new GridLayout(1, 0, HomeScreen.MOVIE_SAPERATOR, 0));
    this.setBorder(null);
    
    
    Map<String, ImageIcon> movies = getMovies();
    // إنشاء لوحة لكل فيلم وإضافتها إلى الإطار
    for (Map.Entry<String, ImageIcon> entry : movies.entrySet()) {
        MovieObjectPanel panel = new MovieObjectPanel(entry.getKey(), entry.getValue());
        this.add(panel);
    }
  }
  
// قراءة بيانات الأفلام من القائمة
      private Map<String, ImageIcon> getMovies() {
      
        Map<String, ImageIcon> movies = new HashMap<>();
        ArrayList <Movie> total = Movie.getMovieList();
        
        //test code remove and uncomment the next commented block 
        ImageIcon whatMenWant = new ImageIcon(getClass().getResource("/res/temp posters/What men want.jpg"));
        ImageIcon Emanc = new ImageIcon(getClass().getResource("/res/temp posters/Emancipation.jpg"));
        ImageIcon FFA = new ImageIcon(getClass().getResource("/res/temp posters/Five feet apart.jpg"));
        ImageIcon lucy = new ImageIcon(getClass().getResource("/res/temp posters/LUCY.jpg"));
        ImageIcon ad = new ImageIcon(getClass().getResource("/res/temp posters/AD astra.jpg"));
        ImageIcon tnbc = new ImageIcon(getClass().getResource("/res/temp posters/The Nightmare Before Cristmass.jpg"));
        ImageIcon ER = new ImageIcon(getClass().getResource("/res/temp posters/Escape room.jpg"));
        ImageIcon ninja = new ImageIcon(getClass().getResource("/res/temp posters/Ternet Ninja.jpg"));
        ImageIcon hell = new ImageIcon(getClass().getResource("/res/temp posters/HellBoy.jpg"));
        ImageIcon am = new ImageIcon(getClass().getResource("/res/temp posters/AboMinable.jpg"));
        ImageIcon pool = new ImageIcon(getClass().getResource("/res/temp posters/The Pool.jpg"));
        ImageIcon tpoh = new ImageIcon(getClass().getResource("/res/temp posters/The Pursuite of happyness.jpg"));
        for (int i = 0; i < HomeScreen.CATAGORY_LENGTH; i++) {
          movies.put("What Men Want" , whatMenWant);
          movies.put("Five Feet Apart" , FFA);
          movies.put("Emancepation" , Emanc);
          movies.put("The  happyness" , tpoh);
          movies.put("LUCY" , lucy);
          movies.put("The   Cristmass" , tnbc);
          movies.put("Escape room" , ER);
          movies.put("AD astra" , ad);
          movies.put("Ternet Ninja" , ninja);
          movies.put("The happyness" , tpoh);
          movies.put("HellBoy" , hell);
          movies.put("AboMinable" , am);
          movies.put("The Pool" , pool);
          movies.put("The   happyness" , tpoh);
        }
        
        
//        int i=0;
//        while(movies.size()<HomeScreen.CATAGORY_LENGTH && i < total.size()){
//          Movie movie = total.get(i);
//          if(movie.getMovieType() == type){
//            movies.put(movie.getMovieTitle(), movie.getMovieImage());
//          }
//          i++;
//        }
        
        return movies;
    }
}