/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import MainPackage.Ticket;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author gtx
 */
public class booked_ticket_form extends javax.swing.JFrame {

    public ArrayList<Ticket> a=new ArrayList<>();
    public static int showtime;
    /**
     * Creates new form booked_ticket_form
     */
    public booked_ticket_form() {
        initComponents();
        this.setVisible(rootPaneCheckingEnabled);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        seat1 = new javax.swing.JLabel();
        seat2 = new javax.swing.JLabel();
        seat3 = new javax.swing.JLabel();
        seat4 = new javax.swing.JLabel();
        seat5 = new javax.swing.JLabel();
        seat6 = new javax.swing.JLabel();
        seat7 = new javax.swing.JLabel();
        seat8 = new javax.swing.JLabel();
        seat9 = new javax.swing.JLabel();
        seat10 = new javax.swing.JLabel();
        seat11 = new javax.swing.JLabel();
        seat12 = new javax.swing.JLabel();
        seat13 = new javax.swing.JLabel();
        seat14 = new javax.swing.JLabel();
        seat15 = new javax.swing.JLabel();
        seat16 = new javax.swing.JLabel();
        seat17 = new javax.swing.JLabel();
        seat18 = new javax.swing.JLabel();
        seat19 = new javax.swing.JLabel();
        seat20 = new javax.swing.JLabel();
        seat21 = new javax.swing.JLabel();
        seat22 = new javax.swing.JLabel();
        seat23 = new javax.swing.JLabel();
        seat24 = new javax.swing.JLabel();
        seat25 = new javax.swing.JLabel();
        seat26 = new javax.swing.JLabel();
        seat27 = new javax.swing.JLabel();
        seat28 = new javax.swing.JLabel();
        seat29 = new javax.swing.JLabel();
        seat30 = new javax.swing.JLabel();
        seat31 = new javax.swing.JLabel();
        seat32 = new javax.swing.JLabel();
        seat33 = new javax.swing.JLabel();
        seat34 = new javax.swing.JLabel();
        seat35 = new javax.swing.JLabel();
        seat36 = new javax.swing.JLabel();
        seat37 = new javax.swing.JLabel();
        seat38 = new javax.swing.JLabel();
        seat39 = new javax.swing.JLabel();
        seat40 = new javax.swing.JLabel();
        seat41 = new javax.swing.JLabel();
        seat42 = new javax.swing.JLabel();
        seat43 = new javax.swing.JLabel();
        seat44 = new javax.swing.JLabel();
        seat45 = new javax.swing.JLabel();
        seat46 = new javax.swing.JLabel();
        seat47 = new javax.swing.JLabel();
        seat48 = new javax.swing.JLabel();
        seat49 = new javax.swing.JLabel();
        seat50 = new javax.swing.JLabel();
        panBook = new javax.swing.JPanel();
        lblBook = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        seat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat1MouseClicked(evt);
            }
        });

        seat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat2MouseClicked(evt);
            }
        });

        seat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat3MouseClicked(evt);
            }
        });

        seat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat4MouseClicked(evt);
            }
        });

        seat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat5MouseClicked(evt);
            }
        });

        seat6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat6MouseClicked(evt);
            }
        });

        seat7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat7MouseClicked(evt);
            }
        });

        seat8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat8MouseClicked(evt);
            }
        });

        seat9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat9MouseClicked(evt);
            }
        });

        seat10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat10MouseClicked(evt);
            }
        });

        seat11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat11MouseClicked(evt);
            }
        });

        seat12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat12MouseClicked(evt);
            }
        });

        seat13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat13MouseClicked(evt);
            }
        });

        seat14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat14MouseClicked(evt);
            }
        });

        seat15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat15MouseClicked(evt);
            }
        });

        seat16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat16MouseClicked(evt);
            }
        });

        seat17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat17MouseClicked(evt);
            }
        });

        seat18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat18MouseClicked(evt);
            }
        });

        seat19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat19MouseClicked(evt);
            }
        });

        seat20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat20MouseClicked(evt);
            }
        });

        seat21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat21MouseClicked(evt);
            }
        });

        seat22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat22MouseClicked(evt);
            }
        });

        seat23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat23MouseClicked(evt);
            }
        });

        seat24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat24MouseClicked(evt);
            }
        });

        seat25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat25MouseClicked(evt);
            }
        });

        seat26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat26MouseClicked(evt);
            }
        });

        seat27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat27MouseClicked(evt);
            }
        });

        seat28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat28MouseClicked(evt);
            }
        });

        seat29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat29MouseClicked(evt);
            }
        });

        seat30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat30MouseClicked(evt);
            }
        });

        seat31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat31MouseClicked(evt);
            }
        });

        seat32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat32MouseClicked(evt);
            }
        });

        seat33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat33MouseClicked(evt);
            }
        });

        seat34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat34MouseClicked(evt);
            }
        });

        seat35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat35MouseClicked(evt);
            }
        });

        seat36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat36MouseClicked(evt);
            }
        });

        seat37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat37MouseClicked(evt);
            }
        });

        seat38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat38MouseClicked(evt);
            }
        });

        seat39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat39MouseClicked(evt);
            }
        });

        seat40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat40MouseClicked(evt);
            }
        });

        seat41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat41MouseClicked(evt);
            }
        });

        seat42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat42MouseClicked(evt);
            }
        });

        seat43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat43MouseClicked(evt);
            }
        });

        seat44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat44MouseClicked(evt);
            }
        });

        seat45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat45MouseClicked(evt);
            }
        });

        seat46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat46MouseClicked(evt);
            }
        });

        seat47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat47MouseClicked(evt);
            }
        });

        seat48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat48MouseClicked(evt);
            }
        });

        seat49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat49MouseClicked(evt);
            }
        });

        seat50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seatBlack.png"))); // NOI18N
        seat50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat50MouseClicked(evt);
            }
        });

        panBook.setBackground(new java.awt.Color(255, 255, 255));
        panBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 3));
        panBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panBookMouseExited(evt);
            }
        });

        lblBook.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblBook.setText("book");
        lblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBookMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panBookLayout = new javax.swing.GroupLayout(panBook);
        panBook.setLayout(panBookLayout);
        panBookLayout.setHorizontalGroup(
            panBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBookLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblBook, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panBookLayout.setVerticalGroup(
            panBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("choos seats to book ");

        panExit.setBackground(new java.awt.Color(255, 255, 255));
        panExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panExitMouseExited(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panExitLayout = new javax.swing.GroupLayout(panExit);
        panExit.setLayout(panExitLayout);
        panExitLayout.setHorizontalGroup(
            panExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panExitLayout.setVerticalGroup(
            panExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExitLayout.createSequentialGroup()
                .addComponent(lblExit)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seat5)
                            .addComponent(seat4)
                            .addComponent(seat3)
                            .addComponent(seat2)
                            .addComponent(seat1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seat10)
                            .addComponent(seat9)
                            .addComponent(seat8)
                            .addComponent(seat7)
                            .addComponent(seat6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seat15)
                            .addComponent(seat14)
                            .addComponent(seat13)
                            .addComponent(seat12)
                            .addComponent(seat11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seat20)
                                    .addComponent(seat19)
                                    .addComponent(seat18)
                                    .addComponent(seat17)
                                    .addComponent(seat16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seat25)
                                    .addComponent(seat24)
                                    .addComponent(seat23)
                                    .addComponent(seat22)
                                    .addComponent(seat21))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seat30)
                                    .addComponent(seat29)
                                    .addComponent(seat28)
                                    .addComponent(seat27)
                                    .addComponent(seat26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seat35)
                                    .addComponent(seat34)
                                    .addComponent(seat33)
                                    .addComponent(seat32)
                                    .addComponent(seat31)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(panBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat40)
                    .addComponent(seat39)
                    .addComponent(seat38)
                    .addComponent(seat37)
                    .addComponent(seat36))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat45)
                    .addComponent(seat44)
                    .addComponent(seat43)
                    .addComponent(seat42)
                    .addComponent(seat41))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seat50)
                            .addComponent(seat49)
                            .addComponent(seat48))
                        .addContainerGap(171, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seat47)
                            .addComponent(seat46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat45))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat5))))
                    .addComponent(panExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(panBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat1MouseClicked
        
        if(seat1.getIcon()==( new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBlack.png"))){
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarbel.png");
        seat1.setIcon(imageIcon);
        Object e=new Object();
        e=seat1;
        a.add((Ticket) e);
        }else{
           ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBlack.png");
           seat1.setIcon(imageIcon); 
        }
    }//GEN-LAST:event_seat1MouseClicked

    private void seat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat2MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat2.setIcon(imageIcon);
    }//GEN-LAST:event_seat2MouseClicked

    private void seat3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat3MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat3.setIcon(imageIcon);
    }//GEN-LAST:event_seat3MouseClicked

    private void seat4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat4MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat4.setIcon(imageIcon);
    }//GEN-LAST:event_seat4MouseClicked

    private void seat5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat5MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat5.setIcon(imageIcon);
    }//GEN-LAST:event_seat5MouseClicked

    private void seat6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat6MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat6.setIcon(imageIcon);
    }//GEN-LAST:event_seat6MouseClicked

    private void seat7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat7MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat7.setIcon(imageIcon);
    }//GEN-LAST:event_seat7MouseClicked

    private void seat8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat8MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat8.setIcon(imageIcon);
    }//GEN-LAST:event_seat8MouseClicked

    private void seat9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat9MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat9.setIcon(imageIcon);
    }//GEN-LAST:event_seat9MouseClicked

    private void seat10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat10MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat10.setIcon(imageIcon);
    }//GEN-LAST:event_seat10MouseClicked

    private void seat11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat11MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat11.setIcon(imageIcon);
    }//GEN-LAST:event_seat11MouseClicked

    private void seat12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat12MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat12.setIcon(imageIcon);
    }//GEN-LAST:event_seat12MouseClicked

    private void seat13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat13MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat13.setIcon(imageIcon);
    }//GEN-LAST:event_seat13MouseClicked

    private void seat14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat14MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat14.setIcon(imageIcon);
    }//GEN-LAST:event_seat14MouseClicked

    private void seat15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat15MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat15.setIcon(imageIcon);
    }//GEN-LAST:event_seat15MouseClicked

    private void seat16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat16MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat16.setIcon(imageIcon);
    }//GEN-LAST:event_seat16MouseClicked

    private void seat17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat17MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat17.setIcon(imageIcon);
    }//GEN-LAST:event_seat17MouseClicked

    private void seat18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat18MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat18.setIcon(imageIcon);
    }//GEN-LAST:event_seat18MouseClicked

    private void seat19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat19MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat19.setIcon(imageIcon);
    }//GEN-LAST:event_seat19MouseClicked

    private void seat20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat20MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat20.setIcon(imageIcon);
    }//GEN-LAST:event_seat20MouseClicked

    private void seat21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat21MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat21.setIcon(imageIcon);
    }//GEN-LAST:event_seat21MouseClicked

    private void seat22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat22MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat22.setIcon(imageIcon);
    }//GEN-LAST:event_seat22MouseClicked

    private void seat23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat23MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat23.setIcon(imageIcon);
    }//GEN-LAST:event_seat23MouseClicked

    private void seat24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat24MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat24.setIcon(imageIcon);
    }//GEN-LAST:event_seat24MouseClicked

    private void seat25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat25MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat25.setIcon(imageIcon);
    }//GEN-LAST:event_seat25MouseClicked

    private void seat26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat26MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat26.setIcon(imageIcon);
    }//GEN-LAST:event_seat26MouseClicked

    private void seat27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat27MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat27.setIcon(imageIcon);
    }//GEN-LAST:event_seat27MouseClicked

    private void seat28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat28MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat28.setIcon(imageIcon);
    }//GEN-LAST:event_seat28MouseClicked

    private void seat29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat29MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat29.setIcon(imageIcon);
    }//GEN-LAST:event_seat29MouseClicked

    private void seat30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat30MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat30.setIcon(imageIcon);
    }//GEN-LAST:event_seat30MouseClicked

    private void seat31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat31MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat31.setIcon(imageIcon);
    }//GEN-LAST:event_seat31MouseClicked

    private void seat32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat32MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat32.setIcon(imageIcon);
    }//GEN-LAST:event_seat32MouseClicked

    private void seat33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat33MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat33.setIcon(imageIcon);
    }//GEN-LAST:event_seat33MouseClicked

    private void seat34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat34MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat34.setIcon(imageIcon);
    }//GEN-LAST:event_seat34MouseClicked

    private void seat35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat35MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat35.setIcon(imageIcon);
    }//GEN-LAST:event_seat35MouseClicked

    private void seat36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat36MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat36.setIcon(imageIcon);
    }//GEN-LAST:event_seat36MouseClicked

    private void seat37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat37MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat37.setIcon(imageIcon);
    }//GEN-LAST:event_seat37MouseClicked

    private void seat38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat38MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat38.setIcon(imageIcon);
    }//GEN-LAST:event_seat38MouseClicked

    private void seat39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat39MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat39.setIcon(imageIcon);
    }//GEN-LAST:event_seat39MouseClicked

    private void seat40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat40MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat40.setIcon(imageIcon);
    }//GEN-LAST:event_seat40MouseClicked

    private void seat41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat41MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat41.setIcon(imageIcon);
    }//GEN-LAST:event_seat41MouseClicked

    private void seat42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat42MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat42.setIcon(imageIcon);
    }//GEN-LAST:event_seat42MouseClicked

    private void seat43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat43MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat43.setIcon(imageIcon);
    }//GEN-LAST:event_seat43MouseClicked

    private void seat44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat44MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat44.setIcon(imageIcon);
    }//GEN-LAST:event_seat44MouseClicked

    private void seat45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat45MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat45.setIcon(imageIcon);
    }//GEN-LAST:event_seat45MouseClicked

    private void seat46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat46MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat46.setIcon(imageIcon);
    }//GEN-LAST:event_seat46MouseClicked

    private void seat47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat47MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat47.setIcon(imageIcon);
    }//GEN-LAST:event_seat47MouseClicked

    private void seat48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat48MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat48.setIcon(imageIcon);
    }//GEN-LAST:event_seat48MouseClicked

    private void seat49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat49MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat49.setIcon(imageIcon);
    }//GEN-LAST:event_seat49MouseClicked

    private void seat50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat50MouseClicked
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\gtx\\Downloads\\Ali-GitHub1\\MovieManagementSystem\\Programming3Project\\src\\res\\seatBarble.png");
        seat50.setIcon(imageIcon);
    }//GEN-LAST:event_seat50MouseClicked

    private void panBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panBookMouseEntered
        panBook.setBackground(new Color (153,0,255));
        lblBook.setForeground(Color.WHITE);
    }//GEN-LAST:event_panBookMouseEntered

    private void lblBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookMouseEntered
        panBook.setBackground(new Color (153,0,255));
        lblBook.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblBookMouseEntered

    private void panBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panBookMouseExited
        panBook.setBackground(Color.WHITE);
        lblBook.setForeground(Color.BLACK);
    }//GEN-LAST:event_panBookMouseExited

    private void lblBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookMouseExited
        panBook.setBackground(Color.WHITE);
        lblBook.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblBookMouseExited

    private void panExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseEntered
        panExit.setBackground(new Color(153,0,255));
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_panExitMouseEntered

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void panExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_panExitMouseClicked

    private void panExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseExited
        panExit.setBackground(Color.WHITE);
        lblExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_panExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        panExit.setBackground(new Color(153,0,255));
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        panExit.setBackground(Color.WHITE);
        lblExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booked_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booked_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booked_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booked_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booked_ticket_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBook;
    private javax.swing.JLabel lblExit;
    private javax.swing.JPanel panBook;
    private javax.swing.JPanel panExit;
    private javax.swing.JLabel seat1;
    private javax.swing.JLabel seat10;
    private javax.swing.JLabel seat11;
    private javax.swing.JLabel seat12;
    private javax.swing.JLabel seat13;
    private javax.swing.JLabel seat14;
    private javax.swing.JLabel seat15;
    private javax.swing.JLabel seat16;
    private javax.swing.JLabel seat17;
    private javax.swing.JLabel seat18;
    private javax.swing.JLabel seat19;
    private javax.swing.JLabel seat2;
    private javax.swing.JLabel seat20;
    private javax.swing.JLabel seat21;
    private javax.swing.JLabel seat22;
    private javax.swing.JLabel seat23;
    private javax.swing.JLabel seat24;
    private javax.swing.JLabel seat25;
    private javax.swing.JLabel seat26;
    private javax.swing.JLabel seat27;
    private javax.swing.JLabel seat28;
    private javax.swing.JLabel seat29;
    private javax.swing.JLabel seat3;
    private javax.swing.JLabel seat30;
    private javax.swing.JLabel seat31;
    private javax.swing.JLabel seat32;
    private javax.swing.JLabel seat33;
    private javax.swing.JLabel seat34;
    private javax.swing.JLabel seat35;
    private javax.swing.JLabel seat36;
    private javax.swing.JLabel seat37;
    private javax.swing.JLabel seat38;
    private javax.swing.JLabel seat39;
    private javax.swing.JLabel seat4;
    private javax.swing.JLabel seat40;
    private javax.swing.JLabel seat41;
    private javax.swing.JLabel seat42;
    private javax.swing.JLabel seat43;
    private javax.swing.JLabel seat44;
    private javax.swing.JLabel seat45;
    private javax.swing.JLabel seat46;
    private javax.swing.JLabel seat47;
    private javax.swing.JLabel seat48;
    private javax.swing.JLabel seat49;
    private javax.swing.JLabel seat5;
    private javax.swing.JLabel seat50;
    private javax.swing.JLabel seat6;
    private javax.swing.JLabel seat7;
    private javax.swing.JLabel seat8;
    private javax.swing.JLabel seat9;
    // End of variables declaration//GEN-END:variables
}
