/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Action.Ticketing.cancelTicket;
import java.awt.Color;

/**
 *
 * @author gtx
 */
public class cancel_ticket_form extends javax.swing.JFrame {

  /**
   * Creates new form cancel_ticket_form
   */
  public cancel_ticket_form() {
    settings();
    initComponents();
    this.setVisible(true);
  }

  void settings() {

    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(cancel_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(cancel_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(cancel_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(cancel_ticket_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TicketIDTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblClickHere = new javax.swing.JLabel();
        panExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        panClick1 = new javax.swing.JPanel();
        lblClick1 = new javax.swing.JLabel();
        NotFoundTicketLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        TicketIDTxt.setBackground(new java.awt.Color(153, 0, 255));
        TicketIDTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TicketIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketIDTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Ticket ID :");

        jLabel2.setText("if you want to see your ID ticket ");

        lblClickHere.setText("CLICK HERE");
        lblClickHere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClickHereMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClickHereMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClickHereMouseExited(evt);
            }
        });

        panExit.setBackground(new java.awt.Color(153, 0, 255));
        panExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panExitMouseExited(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panExitLayout = new javax.swing.GroupLayout(panExit);
        panExit.setLayout(panExitLayout);
        panExitLayout.setHorizontalGroup(
            panExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblExit)
                .addContainerGap())
        );
        panExitLayout.setVerticalGroup(
            panExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExitLayout.createSequentialGroup()
                .addComponent(lblExit)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        panClick1.setBackground(new java.awt.Color(153, 0, 255));
        panClick1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        panClick1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panClick1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panClick1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panClick1MouseExited(evt);
            }
        });

        lblClick1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblClick1.setForeground(new java.awt.Color(255, 255, 255));
        lblClick1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClick1.setText("Done");
        lblClick1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClick1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClick1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClick1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panClick1Layout = new javax.swing.GroupLayout(panClick1);
        panClick1.setLayout(panClick1Layout);
        panClick1Layout.setHorizontalGroup(
            panClick1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClick1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        panClick1Layout.setVerticalGroup(
            panClick1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClick1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(lblClickHere)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(TicketIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(NotFoundTicketLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(panClick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TicketIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NotFoundTicketLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panClick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblClickHere))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TicketIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketIDTxtActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_TicketIDTxtActionPerformed

    private void panExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseEntered
      panExit.setBackground(Color.WHITE);
    }//GEN-LAST:event_panExitMouseEntered

    private void panExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseExited
      panExit.setBackground(new Color(153, 0, 255));
    }//GEN-LAST:event_panExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
      panExit.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
      panExit.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseExited

    private void panExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseClicked
      System.exit(0);
    }//GEN-LAST:event_panExitMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
      this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblClickHereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickHereMouseEntered
      lblClickHere.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblClickHereMouseEntered

    private void lblClickHereMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickHereMouseExited
      lblClickHere.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblClickHereMouseExited

    private void lblClick1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClick1MouseEntered
      panClick1.setBackground(Color.WHITE);
      lblClick1.setForeground(new Color(153, 0, 255));
    }//GEN-LAST:event_lblClick1MouseEntered

    private void lblClick1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClick1MouseExited
      panClick1.setBackground(new Color(153, 0, 255));
      lblClick1.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblClick1MouseExited

    private void panClick1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClick1MouseEntered
      panClick1.setBackground(Color.WHITE);
      lblClick1.setForeground(new Color(153, 0, 255));
    }//GEN-LAST:event_panClick1MouseEntered

    private void panClick1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panClick1MouseExited
      panClick1.setBackground(new Color(153, 0, 255));
      lblClick1.setForeground(Color.WHITE);
    }//GEN-LAST:event_panClick1MouseExited

  private void lblClick1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClick1MouseClicked
    String ticketID = TicketIDTxt.getText();
    String s = TicketIDTxt.getText();
    if (cancelTicket(s) == false) {
      NotFoundTicketLbl.setForeground(Color.RED);
      NotFoundTicketLbl.setText("The Ticket Not Found !");
    } else {
      cancelTicket(s);
      this.dispose();
    }
  }//GEN-LAST:event_lblClick1MouseClicked

  private void lblClickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickHereMouseClicked
    //display user ID ticket /Whatever that is
    //displayIdTicket();
  }//GEN-LAST:event_lblClickHereMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NotFoundTicketLbl;
    private javax.swing.JTextField TicketIDTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClick1;
    private javax.swing.JLabel lblClickHere;
    private javax.swing.JLabel lblExit;
    private javax.swing.JPanel panClick1;
    private javax.swing.JPanel panExit;
    // End of variables declaration//GEN-END:variables
}
