package Interfaces;


import Action.go;
import MainPackage.*;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Obaida
 */
public class HomeScreen extends javax.swing.JFrame {
  public static int SCROLL_INCREMENT_SPEED =16;
  public static int CATAGORY_LENGTH =20;

  /**
   * Creates new form LoginScreen
   */
  public HomeScreen() {
    setting();
    initComponents();
    this.setVisible(true);
    
    this.setIcons(true, false, false);
  }

  public void setting(){
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mainPanel = new javax.swing.JPanel();
    titlebar = new javax.swing.JPanel();
    exitButton = new javax.swing.JLabel();
    seperator3 = new javax.swing.JPanel();
    pageCardPanel = new javax.swing.JPanel();
    homePanel = new javax.swing.JPanel();
    homeScrollPane = new javax.swing.JScrollPane();
    homeScrollPanel = new javax.swing.JPanel();
    actionScrollPane = new javax.swing.JScrollPane();
    gapPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    seperator1 = new javax.swing.JPanel();
    arrowLeft1 = new javax.swing.JLabel();
    arrowRight1 = new javax.swing.JLabel();
    romanceScrollPane = new javax.swing.JScrollPane();
    gapPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    seperator2 = new javax.swing.JPanel();
    arrowLeft2 = new javax.swing.JLabel();
    arrowRight2 = new javax.swing.JLabel();
    dramaScrollPane = new javax.swing.JScrollPane();
    gapPanel3 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    seperator4 = new javax.swing.JPanel();
    arrowLeft3 = new javax.swing.JLabel();
    arrowRight3 = new javax.swing.JLabel();
    sidebar = new javax.swing.JPanel();
    userIcn = new javax.swing.JLabel();
    homeIcnDefault = new javax.swing.JLabel();
    moviesIcnDefault = new javax.swing.JLabel();
    settingsIcnDefault = new javax.swing.JLabel();
    homeIcnSelected = new javax.swing.JLabel();
    moviesIcnSelected = new javax.swing.JLabel();
    settingsIcnSelected = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setPreferredSize(new java.awt.Dimension(1301, 638));
    setResizable(false);

    mainPanel.setBackground(new java.awt.Color(4, 15, 19));
    mainPanel.setLayout(new java.awt.BorderLayout());

    titlebar.setBackground(new java.awt.Color(4, 15, 19));

    exitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    exitButton.setForeground(new java.awt.Color(255, 255, 255));
    exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    exitButton.setText("X");
    exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        exitButtonMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        exitButtonMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        exitButtonMouseExited(evt);
      }
    });

    seperator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

    javax.swing.GroupLayout seperator3Layout = new javax.swing.GroupLayout(seperator3);
    seperator3.setLayout(seperator3Layout);
    seperator3Layout.setHorizontalGroup(
      seperator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 814, Short.MAX_VALUE)
    );
    seperator3Layout.setVerticalGroup(
      seperator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout titlebarLayout = new javax.swing.GroupLayout(titlebar);
    titlebar.setLayout(titlebarLayout);
    titlebarLayout.setHorizontalGroup(
      titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlebarLayout.createSequentialGroup()
        .addContainerGap(354, Short.MAX_VALUE)
        .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(31, 31, 31)
        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    titlebarLayout.setVerticalGroup(
      titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(titlebarLayout.createSequentialGroup()
        .addGroup(titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, Short.MAX_VALUE))
    );

    mainPanel.add(titlebar, java.awt.BorderLayout.PAGE_START);

    pageCardPanel.setLayout(new java.awt.CardLayout());

    homePanel.setBackground(new java.awt.Color(4, 15, 22));

    homeScrollPane.setBackground(new java.awt.Color(4, 15, 22));
    homeScrollPane.getViewport().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
    homeScrollPane.setBorder(null);
    homeScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    homeScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    homeScrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0));
    homeScrollPane.getVerticalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);
    homeScrollPane.setEnabled(false);

    homeScrollPanel.setBackground(new java.awt.Color(4, 15, 22));
    homeScrollPanel.setPreferredSize(new java.awt.Dimension(500, 950));

    actionScrollPane.setBackground(new Color(0,0,0,1));
    actionScrollPane.getViewport ().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
    actionScrollPane.setBorder(null);
    actionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    actionScrollPane.setPreferredSize(new java.awt.Dimension(200, 100));
    actionScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 0));
    actionScrollPane.getHorizontalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);

    gapPanel1.setBackground(new Color(0,0,0,1));

    jLabel3.setBackground(new java.awt.Color(255, 255, 255));
    jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("TOP Action");

    seperator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

    javax.swing.GroupLayout seperator1Layout = new javax.swing.GroupLayout(seperator1);
    seperator1.setLayout(seperator1Layout);
    seperator1Layout.setHorizontalGroup(
      seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 754, Short.MAX_VALUE)
    );
    seperator1Layout.setVerticalGroup(
      seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout gapPanel1Layout = new javax.swing.GroupLayout(gapPanel1);
    gapPanel1.setLayout(gapPanel1Layout);
    gapPanel1Layout.setHorizontalGroup(
      gapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gapPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(gapPanel1Layout.createSequentialGroup()
            .addGap(100, 100, 100)
            .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    gapPanel1Layout.setVerticalGroup(
      gapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapPanel1Layout.createSequentialGroup()
        .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    gapPanel1.setSize(300, 70);

    arrowLeft1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    arrowLeft1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowLeftDefault-01.png"))); // NOI18N
    arrowLeft1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        arrowLeft1MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        arrowLeft1MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        arrowLeft1MouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        arrowLeft1MousePressed(evt);
      }
    });

    arrowRight1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    arrowRight1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowRightDefault-01.png"))); // NOI18N
    arrowRight1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        arrowRight1MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        arrowRight1MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        arrowRight1MouseExited(evt);
      }
    });

    romanceScrollPane.setBackground(new Color(0,0,0,1));
    romanceScrollPane.getViewport().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
    romanceScrollPane.setBorder(null);
    romanceScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    romanceScrollPane.setPreferredSize(new java.awt.Dimension(200, 100));
    romanceScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 0));
    romanceScrollPane.getHorizontalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);

    gapPanel2.setBackground(new Color(0,0,0,1));

    jLabel2.setBackground(new java.awt.Color(255, 255, 255));
    jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("TOP Romance");

    seperator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

    javax.swing.GroupLayout seperator2Layout = new javax.swing.GroupLayout(seperator2);
    seperator2.setLayout(seperator2Layout);
    seperator2Layout.setHorizontalGroup(
      seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 754, Short.MAX_VALUE)
    );
    seperator2Layout.setVerticalGroup(
      seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout gapPanel2Layout = new javax.swing.GroupLayout(gapPanel2);
    gapPanel2.setLayout(gapPanel2Layout);
    gapPanel2Layout.setHorizontalGroup(
      gapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gapPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(gapPanel2Layout.createSequentialGroup()
            .addGap(100, 100, 100)
            .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    gapPanel2Layout.setVerticalGroup(
      gapPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapPanel2Layout.createSequentialGroup()
        .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    gapPanel1.setSize(300, 70);

    arrowLeft2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    arrowLeft2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowLeftDefault-01.png"))); // NOI18N
    arrowLeft2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        arrowLeft2MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        arrowLeft2MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        arrowLeft2MouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        arrowLeft2MousePressed(evt);
      }
    });

    arrowRight2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    arrowRight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowRightDefault-01.png"))); // NOI18N
    arrowRight2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        arrowRight2MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        arrowRight2MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        arrowRight2MouseExited(evt);
      }
    });

    dramaScrollPane.setBackground(new Color(0,0,0,1));
    dramaScrollPane.getViewport().setScrollMode ( JViewport.SIMPLE_SCROLL_MODE );
    dramaScrollPane.setBorder(null);
    dramaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    dramaScrollPane.setPreferredSize(new java.awt.Dimension(200, 100));
    dramaScrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 0));
    dramaScrollPane.getHorizontalScrollBar().setUnitIncrement(SCROLL_INCREMENT_SPEED);

    addRowScrollPanel2();
    homeScrollPanel.add(gapPanel2);
    homeScrollPanel.add(dramaScrollPane);

    gapPanel3.setBackground(new Color(0,0,0,1));

    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
    jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("TOP Drama");

    seperator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 20, 30)));

    javax.swing.GroupLayout seperator4Layout = new javax.swing.GroupLayout(seperator4);
    seperator4.setLayout(seperator4Layout);
    seperator4Layout.setHorizontalGroup(
      seperator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 754, Short.MAX_VALUE)
    );
    seperator4Layout.setVerticalGroup(
      seperator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout gapPanel3Layout = new javax.swing.GroupLayout(gapPanel3);
    gapPanel3.setLayout(gapPanel3Layout);
    gapPanel3Layout.setHorizontalGroup(
      gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gapPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(gapPanel3Layout.createSequentialGroup()
          .addGap(115, 115, 115)
          .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(115, Short.MAX_VALUE)))
    );
    gapPanel3Layout.setVerticalGroup(
      gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapPanel3Layout.createSequentialGroup()
        .addContainerGap(51, Short.MAX_VALUE)
        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(gapPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(gapPanel3Layout.createSequentialGroup()
          .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 82, Short.MAX_VALUE)))
    );

    gapPanel1.setSize(300, 70);

    arrowLeft3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    arrowLeft3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowLeftDefault-01.png"))); // NOI18N
    arrowLeft3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        arrowLeft3MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        arrowLeft3MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        arrowLeft3MouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        arrowLeft3MousePressed(evt);
      }
    });

    arrowRight3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    arrowRight3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ArrowRightDefault-01.png"))); // NOI18N
    arrowRight3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        arrowRight3MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        arrowRight3MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        arrowRight3MouseExited(evt);
      }
    });

    javax.swing.GroupLayout homeScrollPanelLayout = new javax.swing.GroupLayout(homeScrollPanel);
    homeScrollPanel.setLayout(homeScrollPanelLayout);
    homeScrollPanelLayout.setHorizontalGroup(
      homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(gapPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(gapPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(gapPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(homeScrollPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeScrollPanelLayout.createSequentialGroup()
            .addComponent(arrowLeft2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(romanceScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(arrowRight2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(homeScrollPanelLayout.createSequentialGroup()
            .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(arrowLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(arrowLeft3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeScrollPanelLayout.createSequentialGroup()
                .addComponent(dramaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(arrowRight3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(homeScrollPanelLayout.createSequentialGroup()
                .addComponent(actionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(arrowRight1)))))
        .addContainerGap())
    );
    homeScrollPanelLayout.setVerticalGroup(
      homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(homeScrollPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(gapPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(actionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(homeScrollPanelLayout.createSequentialGroup()
            .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(arrowLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(arrowRight1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36)))
        .addGap(37, 37, 37)
        .addComponent(gapPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(romanceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(homeScrollPanelLayout.createSequentialGroup()
            .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(arrowLeft2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(arrowRight2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        .addComponent(gapPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(homeScrollPanelLayout.createSequentialGroup()
            .addGap(134, 134, 134)
            .addGroup(homeScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(homeScrollPanelLayout.createSequentialGroup()
                .addComponent(arrowRight3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
              .addGroup(homeScrollPanelLayout.createSequentialGroup()
                .addComponent(arrowLeft3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))))
          .addGroup(homeScrollPanelLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dramaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );

    addRowScrollPanel1();
    homeScrollPanel.add(gapPanel1);
    homeScrollPanel.add(actionScrollPane);
    addRowScrollPanel3();
    homeScrollPanel.add(gapPanel3);
    homeScrollPanel.add(romanceScrollPane);
    addRowScrollPanel2();

    //homeScrollPanel.setLayout(new GridLayout(0, 1, 10, 0));

    homeScrollPane.setViewportView(homeScrollPanel);

    javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
    homePanel.setLayout(homePanelLayout);
    homePanelLayout.setHorizontalGroup(
      homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(homeScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1241, Short.MAX_VALUE)
    );
    homePanelLayout.setVerticalGroup(
      homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(homeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pageCardPanel.add(homePanel, "CardHome");

    mainPanel.add(pageCardPanel, java.awt.BorderLayout.PAGE_END);

    getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

    sidebar.setBackground(new java.awt.Color(251, 251, 255));
    sidebar.setPreferredSize(new java.awt.Dimension(60, 371));
    sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    userIcn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    userIcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/userDefault.png"))); // NOI18N
    userIcn.setPreferredSize(new java.awt.Dimension(60, 60));
    userIcn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        userIcnMouseClicked(evt);
      }
    });
    sidebar.add(userIcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

    homeIcnDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    homeIcnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/homeDefault.png"))); // NOI18N
    homeIcnDefault.setEnabled(false);
    homeIcnDefault.setPreferredSize(new java.awt.Dimension(60, 40));
    homeIcnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        homeIcnDefaultMouseClicked(evt);
      }
    });
    sidebar.add(homeIcnDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, -1, -1));

    moviesIcnDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    moviesIcnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/movieDefault.png"))); // NOI18N
    moviesIcnDefault.setPreferredSize(new java.awt.Dimension(60, 40));
    moviesIcnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        moviesIcnDefaultMouseClicked(evt);
      }
    });
    sidebar.add(moviesIcnDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, -1, -1));

    settingsIcnDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    settingsIcnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sittingsDefault.png"))); // NOI18N
    settingsIcnDefault.setPreferredSize(new java.awt.Dimension(60, 40));
    settingsIcnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        settingsIcnDefaultMouseClicked(evt);
      }
    });
    sidebar.add(settingsIcnDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, 60, -1));

    homeIcnSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    homeIcnSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/homeSelected.png"))); // NOI18N
    homeIcnSelected.setPreferredSize(new java.awt.Dimension(60, 40));
    sidebar.add(homeIcnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

    moviesIcnSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    moviesIcnSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/movieSelected.png"))); // NOI18N
    sidebar.add(moviesIcnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, -1, -1));

    settingsIcnSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    settingsIcnSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sittingsSelected.png"))); // NOI18N
    settingsIcnSelected.setPreferredSize(new java.awt.Dimension(60, 40));
    sidebar.add(settingsIcnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, -1));

    getContentPane().add(sidebar, java.awt.BorderLayout.WEST);

    setSize(new java.awt.Dimension(1301, 638));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
    System.exit(0);
  }//GEN-LAST:event_exitButtonMouseClicked

  private void arrowLeft2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MouseClicked
//    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftClick-01.png"));
    JScrollBar horizontalScrollBar = romanceScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() - SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowLeft2MouseClicked

  private void arrowRight2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight2MouseClicked
//    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightClick-01.png"));
    JScrollBar horizontalScrollBar = romanceScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() + SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowRight2MouseClicked

  private void arrowLeft2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MouseEntered
    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftHover-01.png"));
  }//GEN-LAST:event_arrowLeft2MouseEntered

  private void arrowLeft2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MouseExited
    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftDefault-01.png"));
  }//GEN-LAST:event_arrowLeft2MouseExited

  private void arrowRight2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight2MouseEntered
    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightHover-01.png"));
  }//GEN-LAST:event_arrowRight2MouseEntered

  private void arrowRight2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight2MouseExited
    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightDefault-01.png"));
  }//GEN-LAST:event_arrowRight2MouseExited

  private void arrowLeft2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft2MousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_arrowLeft2MousePressed

  private void arrowLeft3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MouseClicked
//    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftClick-01.png"));
    JScrollBar horizontalScrollBar = dramaScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() - SCROLL_INCREMENT_SPEED*5);  }//GEN-LAST:event_arrowLeft3MouseClicked

  private void arrowLeft3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MouseEntered
    arrowLeft3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftHover-01.png"));
  }//GEN-LAST:event_arrowLeft3MouseEntered

  private void arrowLeft3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MouseExited
    arrowLeft3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftDefault-01.png"));
  }//GEN-LAST:event_arrowLeft3MouseExited

  private void arrowLeft3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft3MousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_arrowLeft3MousePressed

  private void arrowRight3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight3MouseClicked
//    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightClick-01.png"));
    JScrollBar horizontalScrollBar = dramaScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() + SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowRight3MouseClicked

  private void arrowRight3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight3MouseEntered
    arrowRight3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightHover-01.png"));
  }//GEN-LAST:event_arrowRight3MouseEntered

  private void arrowRight3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight3MouseExited
    arrowRight3.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightDefault-01.png"));
  }//GEN-LAST:event_arrowRight3MouseExited

  private void arrowLeft1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_arrowLeft1MousePressed

  private void arrowLeft1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MouseExited
    arrowLeft1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftDefault-01.png"));
  }//GEN-LAST:event_arrowLeft1MouseExited

  private void arrowLeft1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MouseEntered
    arrowLeft1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftHover-01.png"));
  }//GEN-LAST:event_arrowLeft1MouseEntered

  private void arrowLeft1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowLeft1MouseClicked
    //    arrowLeft2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowLeftClick-01.png"));
    JScrollBar horizontalScrollBar = actionScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() - SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowLeft1MouseClicked

  private void arrowRight1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight1MouseExited
    arrowRight1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightDefault-01.png"));
  }//GEN-LAST:event_arrowRight1MouseExited

  private void arrowRight1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight1MouseEntered
    arrowRight1.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightHover-01.png"));
  }//GEN-LAST:event_arrowRight1MouseEntered

  private void arrowRight1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowRight1MouseClicked
    //    arrowRight2.setIcon(new ImageIcon("F:\\REPO\\MovieManagementSystem\\Programming3Project\\src\\res\\ArrowRightClick-01.png"));
    JScrollBar horizontalScrollBar = actionScrollPane.getHorizontalScrollBar();
    horizontalScrollBar.setValue(horizontalScrollBar.getValue() + SCROLL_INCREMENT_SPEED*5);
  }//GEN-LAST:event_arrowRight1MouseClicked

  private void homeIcnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIcnDefaultMouseClicked
    setIcons(true, false, false);
    //open home panel
  }//GEN-LAST:event_homeIcnDefaultMouseClicked

  private void moviesIcnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviesIcnDefaultMouseClicked
    setIcons(false, true, false);
    //open movie panel
  }//GEN-LAST:event_moviesIcnDefaultMouseClicked

  private void settingsIcnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsIcnDefaultMouseClicked
    setIcons(false, false, true);
    //open settings panel
  }//GEN-LAST:event_settingsIcnDefaultMouseClicked

  private void userIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIcnMouseClicked
    setIcons(false, false, false);
    //open user panel
  }//GEN-LAST:event_userIcnMouseClicked

  private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
    exitButton.setForeground(new Color(162,0,255));
  }//GEN-LAST:event_exitButtonMouseEntered

  private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
    exitButton.setForeground(new Color(251,251,255));
  }//GEN-LAST:event_exitButtonMouseExited



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane actionScrollPane;
  private javax.swing.JLabel arrowLeft1;
  private javax.swing.JLabel arrowLeft2;
  private javax.swing.JLabel arrowLeft3;
  private javax.swing.JLabel arrowRight1;
  private javax.swing.JLabel arrowRight2;
  private javax.swing.JLabel arrowRight3;
  private javax.swing.JScrollPane dramaScrollPane;
  private javax.swing.JLabel exitButton;
  private javax.swing.JPanel gapPanel1;
  private javax.swing.JPanel gapPanel2;
  private javax.swing.JPanel gapPanel3;
  private javax.swing.JLabel homeIcnDefault;
  private javax.swing.JLabel homeIcnSelected;
  private javax.swing.JPanel homePanel;
  private javax.swing.JScrollPane homeScrollPane;
  private javax.swing.JPanel homeScrollPanel;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JLabel moviesIcnDefault;
  private javax.swing.JLabel moviesIcnSelected;
  private javax.swing.JPanel pageCardPanel;
  private javax.swing.JScrollPane romanceScrollPane;
  private javax.swing.JPanel seperator1;
  private javax.swing.JPanel seperator2;
  private javax.swing.JPanel seperator3;
  private javax.swing.JPanel seperator4;
  private javax.swing.JLabel settingsIcnDefault;
  private javax.swing.JLabel settingsIcnSelected;
  private javax.swing.JPanel sidebar;
  private javax.swing.JPanel titlebar;
  private javax.swing.JLabel userIcn;
  // End of variables declaration//GEN-END:variables

  
  
  void addRowScrollPanel1(){
    actionScrollPane.setViewportView(new rowScrollPanel(MainPackage.Type.Action));
  }
  void addRowScrollPanel2(){
    dramaScrollPane.setViewportView(new rowScrollPanel(MainPackage.Type.Drama));
  }
  void addRowScrollPanel3(){
    romanceScrollPane.setViewportView(new rowScrollPanel(MainPackage.Type.Romance));
  }

  private void setIcons(boolean home, boolean movies, boolean settings) {
    homeIcnDefault.setVisible(!home);
    homeIcnDefault.setEnabled(!home);
    homeIcnSelected.setVisible(home);
    homeIcnSelected.setEnabled(home);
    
    moviesIcnDefault.setVisible(!movies);
    moviesIcnDefault.setEnabled(!movies);
    moviesIcnSelected.setVisible(movies);
    moviesIcnSelected.setEnabled(movies);
    
    settingsIcnDefault.setVisible(!settings);
    settingsIcnDefault.setEnabled(!settings);
    settingsIcnSelected.setVisible(settings);
    settingsIcnSelected.setEnabled(settings);  
  }
}

class rowScrollPanel extends JPanel{
  
  Type type;
  
  rowScrollPanel(Type type){
    this.type = type;
    
    this.setBackground(new java.awt.Color(0,0,0,1));
    this.setForeground(new java.awt.Color(255, 255, 255));
    this.setLayout(new GridLayout(1, 0, 30, 5));
    this.setBorder(null);
    
    
    Map<String, ImageIcon> movies = getMovies();
    // إنشاء لوحة لكل فيلم وإضافتها إلى الإطار
    for (Map.Entry<String, ImageIcon> entry : movies.entrySet()) {
        MovieObjectPanel panel = new MovieObjectPanel(entry.getKey(), entry.getValue());
        this.add(panel);
        
    }
  }
// قراءة بيانات الأفلام من القائمة
      private Map<String, ImageIcon> getMovies() {
      
        Map<String, ImageIcon> movies = new HashMap<>();
        ArrayList <Movie> total = Movie.getMovieList();
        
        //test code remove and uncomment the next commented block 
        ImageIcon whatMenWant = new ImageIcon(getClass().getResource("/res/temp posters/What men want.jpg"));
        ImageIcon Emanc = new ImageIcon(getClass().getResource("/res/temp posters/Emancipation.jpg"));
        ImageIcon FFA = new ImageIcon(getClass().getResource("/res/temp posters/Five feet apart.jpg"));
        ImageIcon lucy = new ImageIcon(getClass().getResource("/res/temp posters/LUCY.jpg"));
        for (int i = 0; i < HomeScreen.CATAGORY_LENGTH; i++) {
          movies.put("What Men Want" + i, whatMenWant);
          movies.put("Five Feet Apart" + i, FFA);
          movies.put("Emancepation" + i, Emanc);
          movies.put("LUCY" + i, lucy);
        }
        
        
//        int i=0;
//        while(movies.size()<CATAGORY_LENGTH && i < total.size()){
//          Movie movie = total.get(i);
//          if(movie.getMovieType() == type){
//            movies.put(movie.getMovieTitle(), movie.getMovieImage());
//          }
//          i++;
//        }
//        
        return movies;
    }
}