/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Interfaces.booked_ticket_form;
import MainPackage.*;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author gtx
 */
public class movie_form extends javax.swing.JFrame {

  /**
   * Creates new form movie_form
   */
  Movie movie;

  public movie_form(Movie movie) {
    this.movie = movie;
    settings();
    initComponents();
    this.setMovieInfo();
    this.setVisible(true);
  }

  void settings() {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    NameLbl = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    panExit = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    movieTypeLbl = new javax.swing.JLabel();
    lblTime1 = new javax.swing.JLabel();
    lblTime2 = new javax.swing.JLabel();
    lblTime3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    RatingLbl = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jSeparator2 = new javax.swing.JSeparator();
    jSeparator3 = new javax.swing.JSeparator();
    jLabel6 = new javax.swing.JLabel();
    movieIDLbl = new javax.swing.JLabel();
    PhotoLbl = new javax.swing.JLabel();
    lblExit = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    NameLbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    NameLbl.setForeground(new java.awt.Color(4, 15, 22));
    NameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    NameLbl.setText("1917");

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel1.setText("Movie Type :");

    panExit.setBackground(new java.awt.Color(251, 251, 255));
    panExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    panExit.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        panExitMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        panExitMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        panExitMouseExited(evt);
      }
    });

    javax.swing.GroupLayout panExitLayout = new javax.swing.GroupLayout(panExit);
    panExit.setLayout(panExitLayout);
    panExitLayout.setHorizontalGroup(
      panExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 39, Short.MAX_VALUE)
    );
    panExitLayout.setVerticalGroup(
      panExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 40, Short.MAX_VALUE)
    );

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel4.setText("Show Time :");

    movieTypeLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    movieTypeLbl.setText("Action");

    lblTime1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lblTime1.setText("STA 12/4/2024 11:30");
    lblTime1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTime1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblTime1MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        lblTime1MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        lblTime1MouseExited(evt);
      }
    });

    lblTime2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lblTime2.setText("MON 25/4/2024 11:30");
    lblTime2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTime2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblTime2MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        lblTime2MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        lblTime2MouseExited(evt);
      }
    });

    lblTime3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lblTime3.setText("THU 29/4/2024 11:30");
    lblTime3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTime3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblTime3MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        lblTime3MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        lblTime3MouseExited(evt);
      }
    });

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel5.setText("Rating :");

    RatingLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    RatingLbl.setText("4.5");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel6.setText("Movie ID :");

    movieIDLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    movieIDLbl.setText("199.570.4");

    lblExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lblExit.setText("x");
    lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblExitMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        lblExitMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        lblExitMouseExited(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(60, 60, 60)
            .addComponent(jLabel5))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jLabel6))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel4)))
        .addGap(31, 31, 31)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(110, 110, 110)
            .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(movieTypeLbl)
          .addComponent(RatingLbl)
          .addComponent(movieIDLbl)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(710, 710, 710)
            .addComponent(lblExit))
          .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(lblTime3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lblTime2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
              .addComponent(lblTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(21, 21, 21)
            .addComponent(PhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(308, 308, 308)
        .addComponent(panExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(160, 160, 160)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(NameLbl)
        .addGap(102, 102, 102)
        .addComponent(movieTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(RatingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(movieIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(lblTime1)
        .addGap(18, 18, 18)
        .addComponent(lblTime2)
        .addGap(18, 18, 18)
        .addComponent(lblTime3))
      .addComponent(lblExit)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(370, 370, 370)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(320, 320, 320)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(420, 420, 420)
        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(PhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addComponent(panExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void lblTime3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime3MouseExited
      lblTime3.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTime3MouseExited

    private void lblTime3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime3MouseEntered
      lblTime3.setForeground(new Color(153, 0, 255));
    }//GEN-LAST:event_lblTime3MouseEntered

    private void lblTime2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime2MouseExited
      lblTime2.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTime2MouseExited

    private void lblTime2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime2MouseEntered
      lblTime2.setForeground(new Color(153, 0, 255));
    }//GEN-LAST:event_lblTime2MouseEntered

    private void lblTime1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime1MouseExited
      lblTime1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTime1MouseExited

    private void lblTime1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime1MouseEntered
      lblTime1.setForeground(new Color(153, 0, 255));
    }//GEN-LAST:event_lblTime1MouseEntered

    private void panExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseExited
      panExit.setBackground(new Color(251, 251, 255));
      lblExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_panExitMouseExited

    private void panExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseEntered
      panExit.setBackground(new Color(153, 0, 255));
      lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_panExitMouseEntered

    private void panExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panExitMouseClicked
      System.exit(0);
    }//GEN-LAST:event_panExitMouseClicked

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
      lblExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
      lblExit.setForeground(new Color(162, 0, 255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
      this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblTime1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime1MouseClicked
//        booked_ticket_form.showtime = 0;
//        new booked_ticket_form();
    }//GEN-LAST:event_lblTime1MouseClicked

  private void lblTime2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime2MouseClicked
//        booked_ticket_form.showtime = 1;
//        new booked_ticket_form();
  }//GEN-LAST:event_lblTime2MouseClicked

  private void lblTime3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime3MouseClicked
//        booked_ticket_form.showtime = 2;
//        new booked_ticket_form();
  }//GEN-LAST:event_lblTime3MouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel NameLbl;
  private javax.swing.JLabel PhotoLbl;
  private javax.swing.JLabel RatingLbl;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JLabel lblExit;
  private javax.swing.JLabel lblTime1;
  private javax.swing.JLabel lblTime2;
  private javax.swing.JLabel lblTime3;
  private javax.swing.JLabel movieIDLbl;
  private javax.swing.JLabel movieTypeLbl;
  private javax.swing.JPanel panExit;
  // End of variables declaration//GEN-END:variables

  private void setMovieInfo() {
    PhotoLbl.setIcon(movie.getMovieImage());// poster
    NameLbl.setText(movie.getMovieTitle());// name
    movieTypeLbl.setText(movie.getMovieType().toString());// type
    movieIDLbl.setText(String.valueOf(movie.getMovieID()));// ID
    RatingLbl.setText(String.valueOf(movie.getMovieRating()));// rating
    lblTime1.setText(String.valueOf(movie.getMovieShowTimesList().get(0))); // time1
    lblTime2.setText(String.valueOf(movie.getMovieShowTimesList().get(1))); // time2
    lblTime3.setText(String.valueOf(movie.getMovieShowTimesList().get(2)));// time3
  }
}
