/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import MainPackage.Movie;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author gtx
 */
public class movie_form extends javax.swing.JFrame {

  /**
  * Creates new form movie_form
  */
  Movie movie;
  public movie_form(Movie movie) {
    settings();
    initComponents();
    this.setVisible(true);
    this.movie = movie;
    setup();
  }
  private void settings() {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    movieName = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    movieType = new javax.swing.JLabel();
    lblTime1 = new javax.swing.JLabel();
    lblTime2 = new javax.swing.JLabel();
    lblTime3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    movieRating = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jSeparator2 = new javax.swing.JSeparator();
    jSeparator3 = new javax.swing.JSeparator();
    jLabel6 = new javax.swing.JLabel();
    movieId = new javax.swing.JLabel();
    movieImg = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setAlwaysOnTop(true);
    setUndecorated(true);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    movieName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    movieName.setForeground(new java.awt.Color(4, 15, 22));
    movieName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel1.setText("Movie Type :");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel4.setText("Show Time :");

    movieType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

    lblTime1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lblTime1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTime1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        lblTime1MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        lblTime1MouseExited(evt);
      }
    });

    lblTime2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lblTime2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTime2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        lblTime2MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        lblTime2MouseExited(evt);
      }
    });

    lblTime3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lblTime3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblTime3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        lblTime3MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        lblTime3MouseExited(evt);
      }
    });

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel5.setText("Rating :");

    movieRating.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel6.setText("Movie ID :");

    movieId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

    movieImg.setBackground(new java.awt.Color(255, 255, 255));
    movieImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(201, 201, 201)
            .addComponent(jLabel4)
            .addGap(46, 46, 46)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
              .addComponent(lblTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(33, 33, 33)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(lblTime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(186, 186, 186)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addComponent(movieRating, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(movieImg, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                  .addComponent(movieName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(movieType, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(212, 212, 212)
        .addComponent(jLabel6)
        .addGap(46, 46, 46)
        .addComponent(movieId, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(movieImg, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(movieName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(49, 49, 49)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(movieType, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(42, 42, 42)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(movieRating, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(46, 46, 46)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(movieId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(45, 45, 45)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(lblTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void lblTime3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime3MouseExited
        lblTime3.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTime3MouseExited

    private void lblTime3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime3MouseEntered
        lblTime3.setForeground(new Color(153,0,255));
    }//GEN-LAST:event_lblTime3MouseEntered

    private void lblTime2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime2MouseExited
        lblTime2.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTime2MouseExited

    private void lblTime2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime2MouseEntered
        lblTime2.setForeground(new Color(153,0,255));
    }//GEN-LAST:event_lblTime2MouseEntered

    private void lblTime1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime1MouseExited
        lblTime1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTime1MouseExited

    private void lblTime1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime1MouseEntered
        lblTime1.setForeground(new Color(153,0,255));
    }//GEN-LAST:event_lblTime1MouseEntered


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JLabel lblTime1;
  private javax.swing.JLabel lblTime2;
  private javax.swing.JLabel lblTime3;
  private javax.swing.JLabel movieId;
  private javax.swing.JLabel movieImg;
  private javax.swing.JLabel movieName;
  private javax.swing.JLabel movieRating;
  private javax.swing.JLabel movieType;
  // End of variables declaration//GEN-END:variables

  private void setup() {
    ArrayList<Date> showTimes = movie.getMovieShowTimesList();
    SimpleDateFormat s = new SimpleDateFormat("EEEE yyyy / MM / dd   hh:mm ");
    
    this.movieImg.setIcon(movie.getMovieImage());
    this.movieName.setText(movie.getMovieTitle());
    this.movieType.setText(movie.getMovieType().toString());
    this.movieRating.setText(Integer.toString(movie.getMovieRating()));
    this.movieId.setText(Integer.toString(movie.getMovieID()));
    this.lblTime1.setText(s.format(showTimes.get(0)));
    this.lblTime2.setText(s.format(showTimes.get(1)));
    this.lblTime3.setText(s.format(showTimes.get(2)));
  }

  
}
