/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Marouf.At
 */
public class PaymentScreen extends javax.swing.JFrame {
    public static boolean isOk;

    /**
     * Creates new form PaymentScreen
     */
    public PaymentScreen() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        isOk = false;
        lblphoto.setVisible(false);
        lblPaypalAccount1.setVisible(false);
        lblPaypalPassword.setVisible(false);
        txtAccount.setVisible(false);
        txtPassword.setVisible(false);
        btnOk.setVisible(false);
        seperator.setVisible(false);
        lblOkLabel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radiobtnPaypal = new javax.swing.JRadioButton();
        radiobtnVisaCard = new javax.swing.JRadioButton();
        radiobtnAmazonGiftCard = new javax.swing.JRadioButton();
        pnlPaypal = new javax.swing.JPanel();
        lblphoto = new javax.swing.JLabel();
        seperator = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        txtAccount = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        lblPaypalPassword = new javax.swing.JLabel();
        lblPaypalAccount1 = new javax.swing.JLabel();
        lblOkLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Payment");

        radiobtnPaypal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(radiobtnPaypal);
        radiobtnPaypal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radiobtnPaypal.setText("Paypal Card");
        radiobtnPaypal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnPaypalMouseClicked(evt);
            }
        });

        radiobtnVisaCard.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(radiobtnVisaCard);
        radiobtnVisaCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radiobtnVisaCard.setText("Visa Card");
        radiobtnVisaCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnVisaCardMouseClicked(evt);
            }
        });

        radiobtnAmazonGiftCard.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(radiobtnAmazonGiftCard);
        radiobtnAmazonGiftCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radiobtnAmazonGiftCard.setText("Amazon Gift Card");
        radiobtnAmazonGiftCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnAmazonGiftCardMouseClicked(evt);
            }
        });

        pnlPaypal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPaypal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/PayPalImage.png"))); // NOI18N
        pnlPaypal.add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 330));

        seperator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlPaypal.add(seperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 20, 280));
        pnlPaypal.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 240, -1));
        pnlPaypal.add(txtAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 240, -1));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlPaypal.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 160, -1));

        lblPaypalPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPaypalPassword.setText("Paypal Password: ");
        pnlPaypal.add(lblPaypalPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        lblPaypalAccount1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPaypalAccount1.setText("Paypal Account: ");
        pnlPaypal.add(lblPaypalAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));
        pnlPaypal.add(lblOkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 230, 20));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(radiobtnPaypal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radiobtnVisaCard)
                .addGap(31, 31, 31)
                .addComponent(radiobtnAmazonGiftCard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(420, 420, 420))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlPaypal, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtnPaypal)
                    .addComponent(radiobtnVisaCard)
                    .addComponent(radiobtnAmazonGiftCard))
                .addGap(18, 18, 18)
                .addComponent(pnlPaypal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtnPaypalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnPaypalMouseClicked
        lblphoto.setIcon(new ImageIcon("src/res/PayPalImage.png"));
        lblPaypalAccount1.setText("Paypal Account:");
        lblPaypalPassword.setText("Paypal Password:");
        
        
        lblphoto.setVisible(true);
        lblPaypalAccount1.setVisible(true);
        lblPaypalPassword.setVisible(true);
        txtAccount.setVisible(true);
        txtPassword.setVisible(true);
        btnOk.setVisible(true);
        seperator.setVisible(true);
    }//GEN-LAST:event_radiobtnPaypalMouseClicked

    private void radiobtnVisaCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnVisaCardMouseClicked
        lblphoto.setIcon(new ImageIcon("src/res/VisaCard1.png"));
        lblPaypalAccount1.setText("Visa Account:");
        lblPaypalPassword.setText("Visa Password:");
        
        
        lblphoto.setVisible(true);
        lblPaypalAccount1.setVisible(true);
        lblPaypalPassword.setVisible(true);
        txtAccount.setVisible(true);
        txtPassword.setVisible(true);
        btnOk.setVisible(true);
        seperator.setVisible(true);
    }//GEN-LAST:event_radiobtnVisaCardMouseClicked

    private void radiobtnAmazonGiftCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnAmazonGiftCardMouseClicked
        lblphoto.setIcon(new ImageIcon("src/res/amazonGiftCardImage.png"));
        lblPaypalAccount1.setText("amazon Account:");
        lblPaypalPassword.setText("amazon Password:");
        
        
        lblphoto.setVisible(true);
        lblPaypalAccount1.setVisible(true);
        lblPaypalPassword.setVisible(true);
        txtAccount.setVisible(true);
        txtPassword.setVisible(true);
        btnOk.setVisible(true);
        seperator.setVisible(true);
    }//GEN-LAST:event_radiobtnAmazonGiftCardMouseClicked

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if(txtAccount.getText().isEmpty() || txtPassword.getText().isEmpty()){
            lblOkLabel.setForeground(new Color(255, 102, 102));
            lblOkLabel.setText("Please Dont Leave Empty Fields!");
            isOk = false;
        }else{
            lblOkLabel.setForeground(new Color(51, 204, 0));
            lblOkLabel.setText("                               Done!");
            lblOkLabel.setVisible(true);
            isOk = true;
        }
        lblOkLabel.setVisible(true);
        if(isOk){
            this.dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOkLabel;
    private javax.swing.JLabel lblPaypalAccount1;
    private javax.swing.JLabel lblPaypalPassword;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPaypal;
    private javax.swing.JRadioButton radiobtnAmazonGiftCard;
    private javax.swing.JRadioButton radiobtnPaypal;
    private javax.swing.JRadioButton radiobtnVisaCard;
    private javax.swing.JSeparator seperator;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
